
apiVersion: apps/v1
kind: Deployment

metadata:
  name: trivy-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trivy-app
  template:
    metadata:
      labels:
        app: trivy-app
    spec:
      containers:
        - name: trivy-app-container
          image: localbuild/trivyapptest:latest
          ports:
            - containerPort: 8080