name: C# App Security Scan CI (Advanced)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read          
  security-events: write  
  actions: read           

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Scan repository filesystem
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          exit-code: '1'
          ignore-unfixed: true
          scanners: 'vuln,secret,config'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'

      - name: Upload filesystem scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs-results.sarif'

      - name: Build Docker image
        run: docker build -t trivyapptest:${{ github.sha }} .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'trivyapptest:${{ github.sha }}'
          exit-code: '1'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-image-results.sarif'
      
      - name: Upload image scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-results.sarif'