name: Build and Scan with Trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_scan:
    name: Build and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        id: build-image 
        uses: docker/build-push-action@v5
        with:
          context: . 
          load: true 
          tags: localbuild/trivyapptest:latest 

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0 
        with:
          image-ref: 'localbuild/trivyapptest:latest' 
          format: 'table' 
          exit-code: '1'
          ignore-unfixed: true 
          vuln-type: 'os,library' 
          severity: 'CRITICAL,HIGH,LOW,MEDIUM' 
          trivy-flags: '--vex openvex.json'